name: 'GHCR Versioning Action'
description: 'Advanced semantic versioning with staging/production support'
branding:
  icon: 'git-commit'
  color: 'blue'

inputs:
  current_branch:
    description: 'Current branch name'
    required: true
  commit_message:
    description: 'Last commit message'
    required: true
  prod_branch:
    description: 'Production branch name'
    default: 'main'
  staging_branch:
    description: 'Staging branch name'
    default: 'staging'
  prod_prefix:
    description: 'Tag prefix for production'
    default: 'v'
  staging_prefix:
    description: 'Tag prefix for staging'
    default: 'staging-v'
  major_trigger:
    description: 'Commit message trigger for major version'
    default: '[MAJOR]'
  minor_trigger:
    description: 'Commit message trigger for minor version'
    default: '[MINOR]'
  rc_suffix:
    description: 'Release candidate suffix'
    default: '-rc.'
  fallback_version:
    description: 'Fallback base version'
    default: '0.0.0'
  docker_repository:
    description: 'Docker repository path'
    default: '${{ github.repository }}'

outputs:
  image_tag:
    description: 'Complete Docker image tag'
    value: ${{ steps.version_calc.outputs.image_tag }}
  additional_tag:
    description: 'Additional Docker tag (latest/staging-latest)'
    value: ${{ steps.version_calc.outputs.additional_tag }}
  new_version:
    description: 'New version tag'
    value: ${{ steps.version_calc.outputs.new_version }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository (for tag access)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Calculate versions
      id: version_calc
      shell: bash
      run: |
        export CURRENT_BRANCH="${{ inputs.current_branch }}"
        export COMMIT_MESSAGE="${{ inputs.commit_message }}"
        export PROD_BRANCH="${{ inputs.prod_branch }}"
        export STAGING_BRANCH="${{ inputs.staging_branch }}"
        export PROD_PREFIX="${{ inputs.prod_prefix }}"
        export STAGING_PREFIX="${{ inputs.staging_prefix }}"
        export MAJOR_TRIGGER="${{ inputs.major_trigger }}"
        export MINOR_TRIGGER="${{ inputs.minor_trigger }}"
        export RC_SUFFIX="${{ inputs.rc_suffix }}"
        export FALLBACK_VERSION="${{ inputs.fallback_version }}"
        export DOCKER_REPOSITORY="${{ inputs.docker_repository }}"
        bash ${GITHUB_ACTION_PATH}/src/calculate-version.sh

    - name: Output results
      shell: bash
      run: |
        echo "New version: ${{ steps.version_calc.outputs.new_version }}"
        echo "Docker tag: ${{ steps.version_calc.outputs.image_tag }}"